trigger:
- master

pool:
  name: Azure Pipelines

variables:
- group: 'Build Variables'

steps:
- task: AzureImageBuilderTask@1
  inputs:
    managedIdentity: '$(managedId)'
    imageSource: 'marketplace'
    baseImage: 'MicrosoftWindowsDesktop:Windows-10:19h1-evd'
    baseImagePubOfferSku: 'MicrosoftWindowsDesktop:Windows-10:20h1-evd'
    provisioner: 'powershell'
    packagePath: 'scripts'
    inlineScript: '''& set-executionpolicy remotesigned -scope Process -Force; c:\BuildArtifacts\imageBuildcustomisation.ps1'''
    storageAccountName: '$(storageAccountName)'
    distributeType: 'sig'
    galleryImageId: '$(galleryImageId)'
    replicationRegions: 'WestUS'
    ibSubscription: 'GH-ADO-SP'
    ibAzureResourceGroup: 'RG-WVD-DEVOPS'
    ibLocation: 'eastus'